"""tool configuration

Revision ID: 44adb515ff9e
Revises: 4235caa4c96c
Create Date: 2024-03-09 14:52:41.067153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44adb515ff9e'
down_revision: Union[str, None] = '4235caa4c96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('tool_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'session', 'tool', ['tool_id'], ['id'])
    op.drop_column('session', 'type')
    op.execute('drop type sessiontype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('type', postgresql.ENUM('QUESTION_ANSWERING', 'SUMMARIZATION', name='sessiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'tool_id')
    # ### end Alembic commands ###
