"""question answering history

Revision ID: ab704bdb8fc4
Revises: a0b073206a3d
Create Date: 2024-03-09 13:40:28.794133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab704bdb8fc4'
down_revision: Union[str, None] = 'a0b073206a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('question_answering_history', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'question_answering_history')
    # ### end Alembic commands ###
