"""source id fk removed

Revision ID: 4cd07fe1af9a
Revises: 02cf1afc4766
Create Date: 2024-03-09 12:50:49.190742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd07fe1af9a'
down_revision: Union[str, None] = '02cf1afc4766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_source_source_id_fkey', 'message_source', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('message_source_source_id_fkey', 'message_source', 'source', ['source_id'], ['id'])
    # ### end Alembic commands ###
