"""system prompts

Revision ID: 620cdbb3872a
Revises: d01cbd6dfbd8
Create Date: 2024-03-09 16:00:11.999883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "620cdbb3872a"
down_revision: Union[str, None] = "d01cbd6dfbd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE model SET configuration = configuration || hstore('prompt_system', 'You are an AI assistant. You are helpful, clever, focused on the topic. You provide detailed and direct answers.') WHERE name = 'llama2'"
    )
    op.execute(
        "UPDATE model SET configuration = configuration || hstore('prompt_system', 'Ты - Сайга, русскоязычный автоматический ассистент. Ты разговариваешь с людьми и помогаешь им.') WHERE name = 'saiga2'"
    )
    op.execute(
        "UPDATE model SET configuration = configuration || hstore('prompt_system', 'You are an AI assistant. You are helpful, clever, focused on the topic. You provide detailed and direct answers.') WHERE name = 'openai'"
    )
    op.execute(
        "UPDATE model SET configuration = delete(configuration, 'system_prompt') WHERE name = 'openai'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE model SET configuration = delete(configuration, 'prompt_system')"
    )
    op.execute(
        "UPDATE model SET configuration = configuration || hstore('prompt_system', 'You are a business assistant. You are helpful, clever, and focused on the topic.') WHERE name = 'openai'"
    )
    # ### end Alembic commands ###
