"""br chatbot

Revision ID: 7309e5608771
Revises: af0210575509
Create Date: 2024-03-09 18:59:27.590047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7309e5608771'
down_revision: Union[str, None] = 'af0210575509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM tool WHERE id IN ('bd05ba50-6671-414d-a925-264a1246973f', 'f72bddde-4226-496e-b097-4e114c795ad8', 'd0a6eaa2-05ea-4fe7-9550-897027405c46')")
    op.execute("DELETE FROM model WHERE name IN ('openai', 'llamacpp')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError("No downgrade possible")
    # ### end Alembic commands ###
