"""Question answering simplification

Revision ID: 9406d0039ba7
Revises: 620cdbb3872a
Create Date: 2024-03-09 16:20:42.222990

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import UUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision: str = "9406d0039ba7"
down_revision: Union[str, None] = "620cdbb3872a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

tool_table = sa.table(
    "tool",
    sa.column("id", sa.UUID),
    sa.column("name", sa.String),
    sa.column("title", sa.String),
    sa.column("description", sa.String),
    sa.column("is_system", sa.Boolean),
    sa.column("configuration", postgresql.HSTORE(text_type=sa.Text())),
    sa.column("model_id", sa.UUID),
    sa.column("created_at", sa.DateTime),
    sa.column("updated_at", sa.DateTime),
    sa.column("created_by", sa.String),
    sa.column("updated_by", sa.String),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "question_answering_history")
    op.execute("DELETE FROM message_source")
    op.execute("DELETE FROM message")
    op.execute("DELETE FROM session")
    op.execute("DELETE FROM tool")

    now = datetime.now()
    op.bulk_insert(
        tool_table,
        [
            {
                "id": UUID("d0a6eaa2-05ea-4fe7-9550-897027405c46"),
                "name": "question_answering",
                "title": "Question Answering",
                "description": "Simple question answering tool",
                "is_system": True,
                "configuration": {
                    "max_results": "3",
                    "prompt_answer": """Given the following QUESTION and CONTEXT, create an ANSWER. Use only information from CONTEXT and previous conversation. If you don't know the answer, just say "I don't know." Don't try to make up an answer.

QUESTION:
{question}

CONTEXT:
{summaries}

ANSWER:""",
                    "prompt_compress_question": """Given the previous conversation and a QUESTION below, rephrase the QUESTION to be a STANDALONE QUESTION. In your answer include only the STANDALONE QUESTION and nothing more.

QUESTION: 
{question}

STANDALONE QUESTION:""",
                    "answer_negative": """I don't know.""",
                },
                "model_id": UUID("d9216f23-1f33-4ce1-9b5e-24f16513becc"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("1c539973-7037-455c-a310-17a2bb6b8a90"),
                "name": "question_answering",
                "title": "Вопрос/ответ",
                "description": "Инструмент ответа на вопросы",
                "is_system": True,
                "configuration": {
                    "max_results": "3",
                    "prompt_answer": """На основе приведённого ниже ВОПРОСА и КОНТЕКСТА составь ОТВЕТ. Используй только информацию из КОНТЕКСТА и предыдущего диалога. Если не знаешь ответ, просто скажи "Я не знаю". Не пытайся придумать ответ.

ВОПРОС:
{question}

КОНТЕКСТ:
{summaries}

ОТВЕТ:""",
                    "prompt_compress_question": """На основе предыдущего разговора и ВОПРОСА ниже, перефразируй ВОПРОС так, чтобы он стал САМОДОСТАТОЧНЫМ ВОПРОСОМ. Включи в ответ только САМОДОСТАТОЧНЫЙ ВОПРОС и ничего больше.
    
ВОПРОС:
{question}

САМОДОСТАТОЧНЫЙ ВОПРОС:""",
                    "answer_negative": """Я не знаю.""",
                },
                "model_id": UUID("fe98136f-286f-4344-80c7-82ff7d3b08b5"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("bd05ba50-6671-414d-a925-264a1246973f"),
                "name": "source_analysis",
                "title": "Summary",
                "description": "Source selection and summary creation",
                "is_system": True,
                "configuration": {
                    "max_results": "10",
                    "prompt_analyze_chunk": """Below DOCUMENT and CONTEXT are specified. You should join DOCUMENT and CONTEXT and create a combined SUMMARY. Return only SUMMARY, without thought process.

DOCUMENT:
{intermediary_result}

CONTEXT:
{chunk}

SUMMARY:""",
                    "prompt_analyze_chunk_without_intermediary_results": """Create a SUMMARY for TEXT below. Use only information from TEXT. SUMMARY must include as many key points as possible.

TEXT:
{chunk}

SUMMARY:""",
                    "prompt_combine": """Below DOCUMENTS are specified. Create a SUMMARY for these DOCUMENTS. SUMMARY must include as many key points as possible.

DOCUMENTS:
{results}

SUMMARY:""",
                },
                "model_id": UUID("d9216f23-1f33-4ce1-9b5e-24f16513becc"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("f72bddde-4226-496e-b097-4e114c795ad8"),
                "name": "source_analysis",
                "title": "Краткое содержание",
                "description": "Выбор источников и создание краткого содержания",
                "is_system": True,
                "configuration": {
                    "max_results": "10",
                    "prompt_analyze_chunk": """Ниже представлены ДОКУМЕНТ и КОНТЕКСТ. Нужно объединить ДОКУМЕНТ и КОНТЕКСТ и составить общее КРАТКОЕ СОДЕРЖАНИЕ. Возвращай только КРАТКОЕ СОДЕРЖАНИЕ, без рассуждений.

ДОКУМЕНТ:
{intermediary_result}

КОНТЕКСТ:
{chunk}

КРАТКОЕ СОДЕРЖАНИЕ:""",
                    "prompt_analyze_chunk_without_intermediary_results": """Напиши КРАТКОЕ СОДЕРЖАНИЕ для ТЕКСТА указанного ниже. Используй только информацию из ТЕКСТА. КРАТКОЕ СОДЕРЖАНИЕ должно содержать как можно больше ключевых деталей.

ТЕКСТ:
{chunk}

КРАТКОЕ СОДЕРЖАНИЕ:""",
                    "prompt_combine": """Ниже представлены ДОКУМЕНТЫ. Составь КРАТКОЕ СОДЕРЖАНИЕ для этих ДОКУМЕНТОВ. КРАТКОЕ СОДЕРЖАНИЕ должно содержать как можно больше ключевых деталей.

ДОКУМЕНТЫ:
{results}

КРАТКОЕ СОДЕРЖАНИЕ:""",
                },
                "model_id": UUID("fe98136f-286f-4344-80c7-82ff7d3b08b5"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session", sa.Column("question_answering_history", sa.String(), nullable=True)
    )
    now = datetime.now()
    op.execute("DELETE FROM message_source")
    op.execute("DELETE FROM message")
    op.execute("DELETE FROM session")
    op.execute("DELETE FROM tool")

    op.bulk_insert(
        tool_table,
        [
            {
                "id": UUID("d0a6eaa2-05ea-4fe7-9550-897027405c46"),
                "name": "question_answering",
                "title": "Question Answering",
                "description": "Simple question answering tool",
                "is_system": True,
                "configuration": {
                    "max_results": "3",
                    "prompt_combine": """Given the following QUESTION, CONVERSATION history and DOCUMENTS, create an ANSWER. Use only information included after the question.
If you don't know the answer, just say "I don't know." Don't try to make up an answer.

QUESTION: {question}

CONVERSATION:
{history}

DOCUMENTS:
{summaries}

ANSWER:""",
                    "prompt_combine_without_history": """Given the following QUESTION and DOCUMENTS, create an ANSWER. Use only information included after the question.
If you don't know the answer, just say "I don't know." Don't try to make up an answer.

QUESTION: {question}

DOCUMENTS:
{summaries}

ANSWER:""",
                    "prompt_condense": """Given the following conversation and a followup question, rephrase the followup question to be a standalone question. 
In your answer include only the standalone question and nothing more.

Conversation:
{history}

Follow up question: {question}

Standalone question:""",
                    "prompt_compress_history": """Given the following conversation summary and a followup question and answer, create an updated conversation summary.

CONVERSATION SUMMARY:
{history}

QUESTION: {question}

ANSWER: {answer}

UPDATED CONVERSATION SUMMARY:""",
                    "prompt_compress_without_history": """Given the following question and answer, create a brief conversation summary.

QUESTION: {question}

ANSWER: {answer}

CONVERSATION SUMMARY:""",
                    "answer_negative": """I don't know.""",
                },
                "model_id": UUID("d9216f23-1f33-4ce1-9b5e-24f16513becc"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("1c539973-7037-455c-a310-17a2bb6b8a90"),
                "name": "question_answering",
                "title": "Вопрос/ответ",
                "description": "Инструмент ответа на вопросы",
                "is_system": True,
                "configuration": {
                    "max_results": "3",
                    "prompt_combine": """На основе приведённого ниже ВОПРОСА, РАЗГОВОРА и ДОКУМЕНТОВ составь ОТВЕТ. Используй только информацию после вопроса.
Если не знаешь ответа, просто скажи "Я не знаю". Не пытайся придумать ответ.

ВОПРОС: {question}

РАЗГОВОР:
{history}

ДОКУМЕНТЫ:
{summaries}

ОТВЕТ:""",
                    "prompt_combine_without_history": """На основе приведённого ниже ВОПРОСА и ДОКУМЕНТОВ составь ОТВЕТ. Используй только информацию после вопроса.
Если не знаешь ответа, просто скажи "Я не знаю". Не пытайся придумать ответ.

ВОПРОС: {question}

ДОКУМЕНТЫ:
{summaries}

ОТВЕТ:""",
                    "prompt_condense": """Перефразируй приведенный ниже разговор и последующий вопрос так, чтобы последующий вопрос стал самодостаточным.
В своём ответе включай только самодостаточный вопрос и ничего больше.

Разговор:
{history}

Последний вопрос: {question}

Самодостаточный вопрос:""",
                    "prompt_compress_history": """На основе приведённой ниже выжимки разговора, последующего вопроса и ответа составь обновлённую выжимку из разговора.

ВЫЖИМКА РАЗГОВОРА:
{history}

ВОПРОС: {question}

ОТВЕТ: {answer}

ОБНОВЛЕННАЯ ВЫЖИМКА РАЗГОВОРА:""",
                    "prompt_compress_without_history": """На основе приведённого ниже вопроса и ответа составь краткую выжимку из разговора.

ВОПРОС: {question}

ОТВЕТ: {answer}

ВЫЖИМКА РАЗГОВОРА:""",
                    "answer_negative": """Я не знаю.""",
                },
                "model_id": UUID("fe98136f-286f-4344-80c7-82ff7d3b08b5"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("bd05ba50-6671-414d-a925-264a1246973f"),
                "name": "source_analysis",
                "title": "Summary",
                "description": "Source selection and summary creation",
                "is_system": True,
                "configuration": {
                    "prompt_analyze_chunk": """We have a summary of some document.


{intermediary_result}


We have the opportunity to refine the summary (only if needed) with some more context below.


{chunk}


Given the new context, refine the original summary to include as many key details as possible.
If the context isn't useful, return the original summary.

SUMMARY:""",
                    "prompt_analyze_chunk_without_intermediary_results": """Write a summary of the following. 
Try to use only the information provided. 
Try to include as many key details as possible.


{chunk}


SUMMARY:""",
                    "prompt_combine": """We have summaries of a few documents.


{results}


Create a combined summary, containing as many key details as possible from existing summaries above.

COMBINED SUMMARY:""",
                },
                "model_id": UUID("d9216f23-1f33-4ce1-9b5e-24f16513becc"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("f72bddde-4226-496e-b097-4e114c795ad8"),
                "name": "source_analysis",
                "title": "Краткое содержание",
                "description": "Выбор источников и создание краткого содержания",
                "is_system": True,
                "configuration": {
                    "prompt_analyze_chunk": """У нас есть краткое содержание документа.


{intermediary_result}


Мы можем расширить краткое содержание (только если необходимо) с помощью дополнительного контекста ниже.


{chunk}


С помощью нового контекста уточни исходное краткое содержание, чтобы включить в него как можно больше ключевых деталей.
Если контекст не оказался полезным, верни исходное краткое содержание.

КРАТКОЕ СОДЕРЖАНИЕ:""",
                    "prompt_analyze_chunk_without_intermediary_results": """Напиши краткое содержание следующего текста. 
Используй только информацию указанную ниже.
Постарайся включить в краткое содержание как можно больше ключевых деталей.


{chunk}


КРАТКОЕ СОДЕРЖАНИЕ:""",
                    "prompt_combine": """У нас есть краткие содержания нескольких документов.


{results}


Создай общее краткое содержание, включающее как можно больше ключевых деталей из имеющихся кратких содержаний.

ОБЩЕЕ КРАТКОЕ СОДЕРЖАНИЕ:""",
                },
                "model_id": UUID("fe98136f-286f-4344-80c7-82ff7d3b08b5"),
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
        ],
    )
    # ### end Alembic commands ###
