"""session type

Revision ID: a0b073206a3d
Revises: 4cd07fe1af9a
Create Date: 2024-03-09 13:01:40.798152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b073206a3d'
down_revision: Union[str, None] = '4cd07fe1af9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE sessiontype RENAME VALUE 'CHAT' TO 'QUESTION_ANSWERING'")
    op.execute("ALTER TYPE sessiontype ADD VALUE IF NOT EXISTS 'SUMMARIZATION'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE sessiontype RENAME VALUE 'QUESTION_ANSWERING' TO 'CHAT'")
    # ### end Alembic commands ###
