"""openai model

Revision ID: d323a2eea125
Revises: 44adb515ff9e
Create Date: 2024-03-09 15:22:17.190945

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import UUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision: str = "d323a2eea125"
down_revision: Union[str, None] = "44adb515ff9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

model_table = sa.table(
    "model",
    sa.column("id", sa.UUID),
    sa.column("name", sa.String),
    sa.column("title", sa.String),
    sa.column("description", sa.String),
    sa.column("is_system", sa.Boolean),
    sa.column("configuration", postgresql.HSTORE(text_type=sa.Text())),
    sa.column("created_at", sa.DateTime),
    sa.column("updated_at", sa.DateTime),
    sa.column("created_by", sa.String),
    sa.column("updated_by", sa.String),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.now()
    op.bulk_insert(
        model_table,
        [
            {
                "id": UUID("32DE1626-DD2B-478C-A965-5CB585B4FCAA"),
                "name": "openai",
                "title": "GPT-4",
                "description": "GPT-4 with standard (4K) context window",
                "is_system": True,
                "configuration": {
                    "model": "gpt-4",
                    "context_length": "4096",
                    "top_p": "0.9",
                    "repeat_penalty": "1.2",
                    "temperature": "1.0",
                    "timeout": "60",
                    "system_prompt": "You are a business assistant. You are helpful, clever, and focused on the topic.",
                },
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("CAE82C3C-54C4-4A28-B220-D0840A133A1B"),
                "name": "openai",
                "title": "GPT-4 32K",
                "description": "GPT-4 with longer (32K) context window",
                "is_system": True,
                "configuration": {
                    "model": "gpt-4-32k",
                    "context_length": "32768",
                    "top_p": "0.9",
                    "repeat_penalty": "1.2",
                    "temperature": "1.0",
                    "timeout": "60",
                    "system_prompt": "You are a business assistant. You are helpful, clever, and focused on the topic.",
                },
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
            {
                "id": UUID("7B7F6ED8-C760-46E8-B7B9-C17605956EF5"),
                "name": "openai",
                "title": "GPT-4 Turbo (Preview)",
                "description": "GPT-4 Turbo - a cheaper preview version, with 128K tokens context window",
                "is_system": True,
                "configuration": {
                    "model": "gpt-4-1106-preview",
                    "context_length": "128000",
                    "top_p": "0.9",
                    "repeat_penalty": "1.2",
                    "temperature": "1.0",
                    "timeout": "60",
                    "system_prompt": "You are a business assistant. You are helpful, clever, and focused on the topic.",
                },
                "created_at": now,
                "updated_at": now,
                "created_by": "system",
                "updated_by": "system",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM model WHERE name = 'openai'")
    # ### end Alembic commands ###
