"""sources in analysis

Revision ID: f3b649bf4dcd
Revises: d7f7168dca46
Create Date: 2024-03-09 17:54:52.022748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b649bf4dcd'
down_revision: Union[str, None] = 'd7f7168dca46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_source', sa.Column('source_title', sa.String(), nullable=True))
    op.add_column('message_source', sa.Column('subtitle', sa.String(), nullable=True))
    op.add_column('message_source', sa.Column('chunk', sa.Integer(), nullable=True))
    op.add_column('message_source', sa.Column('total_chunks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_source', 'total_chunks')
    op.drop_column('message_source', 'chunk')
    op.drop_column('message_source', 'subtitle')
    op.drop_column('message_source', 'source_title')
    # ### end Alembic commands ###
